### ISSUE TITLE
x-coord OOB Check Integration and Testing

### ISSUE THREAD

**Issue by john-fike** [msudesigncpr/libcolonyfind#1]
libcolonyfind has seen some changes on [oop-oob](https://github.com/msudesigncpr/libcolonyfind/tree/oop-oob)

- Added a check that removes colonies if they will trigger an x coord out of bounds error. This should hopefully fix the whole "we can't go there without ripping our camera assembly apart issue.
- Change entire coord system to be in mm-offsets from the center of the image, and am now removing colonies smaller than 1 mm wide. 
- I have refactored libcolonyfind to provide a class `ColonyFinder` with a couple of functions that run the full process, create and return annotated images, and return colony coord dicts. 
- I made `annotate_images()` accept an array of images, and return an array of images. I did this because I was under the impression this is what Will wanted. I can change it back to accepting a path if it's easier. 

I have tested most of this, but I have yet to run it on the CPR computer with the process control code. 
After this is done, I will begin tests for spec 1.2.3 -- [wiki for that](https://github.com/msudesigncpr/libcolonyfind/wiki/False-Positive-Tests)

**Comment by john-fike** [comment]
More on the math @w-culhane please sanity check this.

The center of the two petri dishes closest to the 8020 frame are `66.11 mm` away from the x-axis origin ([source](https://github.com/msudesigncpr/slate-ui/blob/tonic/src/slate_ui/baseplate_locations.json))
The closest colonies can be to the x-axis origin is `38.34 mm` ([source](https://github.com/msudesigncpr/libmotorctrl/blob/tonic/src%2Flibmotorctrl%2Fdrive_manager.py#L76-L79
))

So, I think (but probably not) my code checks to see if colonies are `66.11-38.34 = 27.77 mm` away from the center of the petri dish. 
Since we change the coordinate system from having an origin at the top left of the image to the center, we subtract `0.5 * img_width` from the x coord and `0.5 * img_height` from the y coord. And if I'm remembering how everything is oriented, that means that...
uh
The y coord of the colony... 
Can't be less than `-27.77 mm` ...?
idk shits fucked yall get to help me with this next week

**Comment by john-fike** [comment]
This should be the code that does all that

Check
``` 
main_is_out_bounds = (baseplate_coord_transform(main_colony_x, main_colony_y)[1] < -27.77) and (petri_dish_counter == 0 or petri_dish_counter == 1) # TODO: Make petri dish counter numbers constants after order is finalized. 
```
Transform
```
def baseplate_coord_transform(x, y, gsd_x = CONSTANTS.GSD_X, gsd_y = CONSTANTS.GSD_Y, img_width = CONSTANTS.IMG_WIDTH, img_height = CONSTANTS.IMG_HEIGHT):
    '''
    turns pixel coorinates to mm offsets from the center of the image
    '''
    center_x = 0.5 * img_width
    center_y = 0.5 * img_height

    x = ((x - center_x)/img_width) * gsd_x # FIXME THIS IS PROBABLY WRONG
    y = ((y - center_y)/img_height) * gsd_y

    return [x, y]
```

**Comment by w-culhane** [comment]
That seems like a valid approach to me. I'd suggest:
- Refactor so that the conversion to mm from the center occurs immediately when you parse CFU's output (like [here](https://github.com/msudesigncpr/libcolonyfind/blob/78aa3d79588f4cc3443116af3622c240c4509042/src/libcolonyfind/colony_finder.py#L116-L118)). The mm from center number is a lot more directly meaningful & easier to handle (and I don't think the pixel offset is directly used for anything).
- Move -27.44 to the constants file
- With the above changes, I'd simplify the OOB check to:
```python
colony_exceeds_position_limit = False
if petri_dish_counter in {0, 1}:
    colony_exceeds_position_limit = main_colony_x < CONSTANTS.XLIMIT_MIN
```
where `CONSTANTS.XLIMIT_MIN` is -27.44.
- I agree that the coordinate conversion x & y swap is confusing. I'd propose either:
  1) Swapping the definitions of x and y in your code or
  2) I can bring back the line from the earlier UI to rotate the image before calling `libcolonyfind`.

That way the x and y definitions in libcolonyfind would be consistent with the drive positioning code.

**Comment by john-fike** [comment]
Refactor being done on [oop-oob](https://github.com/msudesigncpr/libcolonyfind/tree/oop-oob)

I am going to change [parse_cfu_csv()](https://github.com/msudesigncpr/libcolonyfind/blob/dc3d89ea07deffe8ae05fe4d6540919a096e4748/src/libcolonyfind/colony_finder.py#L121) to convert to mm from center

and simplify oob check.

this is going to break everything 

I am also going to make everything oopy, which should cancel all of the shit I break out and the code will run perfect first time

![image](https://github.com/msudesigncpr/libcolonyfind/assets/80931988/8e725e44-6255-434d-8535-267fe493329c)
man this dalle thing is getting good

**Comment by john-fike** [comment]
!remindme fix annotation because its using pixel coords and ive changed everything to mm from center

**Comment by john-fike** [comment]
![Image](https://github.com/msudesigncpr/libcolonyfind/assets/80931988/0872a6da-afb3-4b15-a5d6-b42681032390)

some initial results. still working on random bugs. 
I built opencfu using github actions to process this image if ur wondering why there are like 200 commits with 1 change. will squash after merge.

some other changes:
- annotate_images now returns an array of images for you to save to whatever name/path you'd like
- libcolonyfind now exposes a class to import and use

I'll obviously document this better but this is my test script to give you an idea of how process control will have to chage
```python
from libcolonyfind.colony_finder import ColonyFinder
# import pytest
import cv2

def test_colony_finder():
    raw_image_path='../../4-5-images'
    csv_out_path='output\cfu-csv'
    img = cv2.imread('4-5-images\p0.jpg')
    cf = ColonyFinder(raw_image_path, csv_out_path, [img])
    cf.run_full_proc() # Process images and annotate
    print(cf.get_coords())
    image = cf.get_annot_images()
    image = image[0]
    image = cv2.resize(image, (640, 640), interpolation=cv2.INTER_AREA)
    cv2.imshow('image', image)
    cv2.waitKey(0)

if __name__ == "__main__":
    test_colony_finder()
```

**Comment by john-fike** [comment]
![Image](https://github.com/msudesigncpr/libcolonyfind/assets/80931988/79ea7785-316c-451f-852d-b1f2cde67720)

this is what a mm looks like, and is what I will be using for spec 1.2.3 tests. 
This is better for being sure baseplate coords sent to motor controllers are able to withstand up to 1 mm of error being introduced. However, supposedly, colonies could be as small as 1 mm _wide_ . I am currently removing colonies that are smaller than 1 mm wide. Obviously, if we have 0.4 mm of error being introduced to coords by the motor control software, that is going to make it hard to pick colonies 1 mm wide. 

idk

itll be fine

**Comment by john-fike** [comment]
6320882429133ad85208b6d0affd64c42466fe7a

merged oop-oob. Should work nominally. Couldn't test WSL/OpenCFU stuff.
process control will need to be changed to work with the new class structure. it should look pretty similar to the code in the readme. 

maybe something like this...
```
        cf = ColonyFinder(self.raw_image_path, self.csv_out_dir, self.imgs_for_annotate)        
        cf.run_full_proc()

        images = cf.get_annot_images()
        
        for index, image in enumerate(images):
            cv2.imwrite('../../output/annotated-images' + str(index) + ".jpg", image)

        raw_baseplate_coords_dict = cf.get_coords()
```

lmk what breaks.

**Comment by john-fike** [comment]
fixed some annotation and random sampling bugs. 
I added some boxes and colors to help tell which well each sample went to 
![image](https://github.com/msudesigncpr/libcolonyfind/assets/80931988/ecb29cad-238c-4d5a-afa5-4ac2af78832c)

**Comment by john-fike** [comment]
Avoidance of colonies OOB in x-direction is working. Closing issue.
